<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><i class="fa fa-home" aria-hidden="true"></i> Logo</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="#"><i class="fa fa-globe" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                        <li class="dropdown">
                            <a href="#"
                               class="dropdown-toggle"
                               data-toggle="dropdown"
                               role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                <i class="fa fa-bell" aria-hidden="true"></i>
                                <span class="badges">5</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><img src="/img/ava.jpg" class="img-circle"></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header>
    <div class="container">
        <aside class="left-sidebar">
            <div class="profile block">

                <h4>My Profile</h4>

                <div class="user-avatar">
                    <img src="/img/ava.jpg" class="img-circle">
                </div>

                <ul class="user-info">
                    <li><i class="fa fa-pencil" aria-hidden="true"></i> Designer, UI</li>
                    <li><i class="fa fa-home" aria-hidden="true"></i> London, UK</li>
                    <li><i class="fa fa-birthday-cake" aria-hidden="true"></i> April 1, 1988</li>
                </ul>

            </div>
            <div class="media">
                <ul class="accordion">
                    <li class="accordion-item">
                        <input type="checkbox" class="accordion-toggle" id="my-group-accordion" hidden>
                        <label class="accordion-trigger" for="my-group-accordion">
                            <i class="fa fa-refresh" aria-hidden="true"></i>
                            My Groups
                        </label>
                        <div class="accordion-target">
                            <p>
                                Some text..
                            </p>
                        </div>
                    </li>
                    <li class="accordion-item">
                        <input type="checkbox" class="accordion-toggle" id="my-event-accordion" hidden>
                        <label class="accordion-trigger" for="my-event-accordion">
                            <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                            My Events
                        </label>
                        <div class="accordion-target">
                            <p>
                                Some other text..
                            </p>
                        </div>
                    </li>
                    <li class="accordion-item">
                        <input type="checkbox" class="accordion-toggle" id="my-photo-accordion" hidden>
                        <label class="accordion-trigger" for="my-photo-accordion">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            My Photos
                        </label>
                        <div class="accordion-target">
                            <p>
                                Photos
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="interests block">
                <h4>Interests</h4>
                <p>
                    <span class="tag-interest-h1">News</span>
                    <span class="tag-interest-h2">W3Schools</span>
                    <span class="tag-interest-h3">Labels</span>
                    <span class="tag-interest-h4">Games</span>
                    <span class="tag-interest-m1">Friends</span>
                    <span class="tag-interest-m2">Games</span>
                    <span class="tag-interest-m3">Friends</span>
                    <span class="tag-interest-m4">Food</span>
                    <span class="tag-interest-l1">Design</span>
                    <span class="tag-interest-l2">Art</span>
                    <span class="tag-interest-l3">Photos</span>
                </p>
            </div>

            <div class="alert alert-info alert-dismissible additional-style-alert" role="alert">
                <button type="button"
                        class="close"
                        data-dismiss="alert"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>Hey!</strong><br>
                People are looking at your profile. Find out who.
            </div>
        </aside>
        <article>
            <div class="post-form block">
                <h4>Write news</h4>
                <form id="write-news-form" action="" method="post">
                    <input type="text" class="form-control" name="title-news" placeholder="Write title for Your post... ">
                    <textarea class="form-control text-news" rows="10" name="text-news"></textarea>
                    <button type="submit" class="btn btn-info btn-service btn-hide">
                        <i class="fa fa-pencil" aria-hidden="true"></i> Post
                    </button>
                </form>
            </div>

            <!--<div class="post block-article row">
                <div class="author-avatar">
                    <img src="/img/ava.jpg">
                </div>
                <div class="author-name">
                    <h3>John Doe</h3>
                </div>
                <div class="post-time">
                    16 min.
                </div>
                <div class="title-post">
                    <h2>Lorem ipsum dolor sit amet</h2>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
                <div class="post-image">
                    <img src="/img/img-post.jpg" class="img-responsive">
                </div>
                <div class="post-buttons">
                    <button type="button" class="btn btn-info btn-service">
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> Like
                    </button>
                    <button type="button" class="btn btn-info btn-service">
                        <i class="fa fa-comment" aria-hidden="true"></i> Comment
                    </button>
                    <button type="button" data-id="123" class="btn btn-info btn-service btn-delete">
                        <i class="fa fa-trash" aria-hidden="true"></i> Delete
                    </button>
                </div>

            </div>

            <div class="post block-article row">
                <div class="author-avatar">
                    <img src="/img/ava.jpg">
                </div>
                <div class="author-name">
                    <h3>John Doe</h3>
                </div>
                <div class="post-time">
                    16 min.
                </div>
                <div class="title-post">
                    <h2>Lorem ipsum dolor sit amet</h2>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
                <div class="post-image">
                    <img src="/img/img-post.jpg" class="img-responsive">
                </div>
                <div class="post-buttons">
                    <button type="button" class="btn btn-info btn-service">
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> Like
                    </button>
                    <button type="button" class="btn btn-info btn-service">
                        <i class="fa fa-comment" aria-hidden="true"></i> Comment
                    </button>
                    <button type="button" data-id="123" class="btn btn-info btn-service btn-delete">
                        <i class="fa fa-trash" aria-hidden="true"></i> Delete
                    </button>
                </div>

                <div class="write-comment">
                    <h4>Write your comment:</h4>

                    <textarea class="form-control" rows="3"></textarea>

                    <button type="button" class="btn btn-info btn-service">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i> Add comment
                    </button>
                </div>

                <div class="comments">
                    <h4>Comments:</h4>

                    <div class="row">
                        <div class="user-avatar"><img src="/img/ava.jpg"></div>
                        <div class="comment-info">
                            <div class="row">
                                <div class="username">John Doe</div>
                                <div class="comment-time"> 16 min</div>
                                <div class="comment-delete"> <i class="fa fa-times" aria-hidden="true"></i></div>
                                <div class="text-comment">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                        incididunt ut
                                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                        exercitation ullamco
                                        laboris nisi ut aliquip ex ea commodo consequat.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>-->
        </article>
        <aside class="right-sidebar">
            <div class="upcoming-events block">
                <h5>Upcoming events:</h5>
                <img src="/img/ava.jpg" class="img-responsive">
                <p><span class="name-events">Holidays</span></p>
                <p>Friday 15:00</p>
                <div class="btn-group btn-group-size">
                    <button type="button" class="btn btn-info btn-information">
                        Info
                    </button>
                </div>
            </div>
            <div class="friend-request block">

                <h4>Friend Request</h4>
                <div class="friend-avatar">
                    <img src="/img/ava.jpg">
                </div>
                <h5>John Doe</h5>
                <div class="btn-group btn-group-size">
                    <button type="button" class="btn btn-danger btn-refuse">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </button>

                    <button type="button" class="btn btn-success btn-success">
                        <i class="fa fa-check" aria-hidden="true"></i>
                    </button>
                </div>


            </div>
            <div class="ads block">
                <p>ADS</p>
            </div>
            <div class="notice block">
                <i class="fa fa-bug" aria-hidden="true"></i>
            </div>
        </aside>
    </div>
    <footer>
        <div class="footer-info">
            <h5>Footer</h5>
        </div>
        <div class="copyright">
                Powered by <a href="#" target="_blank">Skiy11</a>
        </div>
    </footer>
    <script
            src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/js/write-news.js" type="text/javascript"></script>
    <script src="/js/scrolling.js" type="text/javascript"></script>
    <script src="/js/comments.js" type="text/javascript"></script>
</body>
</html>